// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GCToBS.proto
// Protobuf C++ Version: 4.26.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_GCToBS_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_GCToBS_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 4026000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_GCToBS_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_GCToBS_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_GCToBS_2eproto;
namespace GCToBS {
class AskGateAddress;
struct AskGateAddressDefaultTypeInternal;
extern AskGateAddressDefaultTypeInternal _AskGateAddress_default_instance_;
class OneClinetLogin;
struct OneClinetLoginDefaultTypeInternal;
extern OneClinetLoginDefaultTypeInternal _OneClinetLogin_default_instance_;
}  // namespace GCToBS
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace GCToBS {
enum MsgNum : int {
  eMsgToBSFromGC_Begin = 32768,
  eMsgToBSFromGC_AskGateAddress = 32769,
  eMsgToBSFromGC_OneClinetLogin = 32770,
  eMsgToBSFromGC_End = 33000,
};

bool MsgNum_IsValid(int value);
extern const uint32_t MsgNum_internal_data_[];
constexpr MsgNum MsgNum_MIN = static_cast<MsgNum>(32768);
constexpr MsgNum MsgNum_MAX = static_cast<MsgNum>(33000);
constexpr int MsgNum_ARRAYSIZE = 33000 + 1;
const ::google::protobuf::EnumDescriptor*
MsgNum_descriptor();
template <typename T>
const std::string& MsgNum_Name(T value) {
  static_assert(std::is_same<T, MsgNum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MsgNum_Name().");
  return ::google::protobuf::internal::NameOfEnum(MsgNum_descriptor(), value);
}
inline bool MsgNum_Parse(absl::string_view name, MsgNum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgNum>(
      MsgNum_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class OneClinetLogin final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GCToBS.OneClinetLogin) */ {
 public:
  inline OneClinetLogin() : OneClinetLogin(nullptr) {}
  ~OneClinetLogin() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OneClinetLogin(
      ::google::protobuf::internal::ConstantInitialized);

  inline OneClinetLogin(const OneClinetLogin& from) : OneClinetLogin(nullptr, from) {}
  inline OneClinetLogin(OneClinetLogin&& from) noexcept
      : OneClinetLogin(nullptr, std::move(from)) {}
  inline OneClinetLogin& operator=(const OneClinetLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline OneClinetLogin& operator=(OneClinetLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OneClinetLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const OneClinetLogin* internal_default_instance() {
    return reinterpret_cast<const OneClinetLogin*>(
        &_OneClinetLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(OneClinetLogin& a, OneClinetLogin& b) { a.Swap(&b); }
  inline void Swap(OneClinetLogin* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OneClinetLogin* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OneClinetLogin* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<OneClinetLogin>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OneClinetLogin& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OneClinetLogin& from) { OneClinetLogin::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(OneClinetLogin* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "GCToBS.OneClinetLogin"; }

 protected:
  explicit OneClinetLogin(::google::protobuf::Arena* arena);
  OneClinetLogin(::google::protobuf::Arena* arena, const OneClinetLogin& from);
  OneClinetLogin(::google::protobuf::Arena* arena, OneClinetLogin&& from) noexcept
      : OneClinetLogin(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUinFieldNumber = 2,
    kSessionidFieldNumber = 3,
    kPlatFieldNumber = 4,
    kLoginSuccessFieldNumber = 5,
    kNsidFieldNumber = 6,
    kMsgnumFieldNumber = 1,
  };
  // optional string uin = 2;
  bool has_uin() const;
  void clear_uin() ;
  const std::string& uin() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uin(Arg_&& arg, Args_... args);
  std::string* mutable_uin();
  PROTOBUF_NODISCARD std::string* release_uin();
  void set_allocated_uin(std::string* value);

  private:
  const std::string& _internal_uin() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uin(
      const std::string& value);
  std::string* _internal_mutable_uin();

  public:
  // optional string sessionid = 3;
  bool has_sessionid() const;
  void clear_sessionid() ;
  const std::string& sessionid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sessionid(Arg_&& arg, Args_... args);
  std::string* mutable_sessionid();
  PROTOBUF_NODISCARD std::string* release_sessionid();
  void set_allocated_sessionid(std::string* value);

  private:
  const std::string& _internal_sessionid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sessionid(
      const std::string& value);
  std::string* _internal_mutable_sessionid();

  public:
  // optional uint32 plat = 4;
  bool has_plat() const;
  void clear_plat() ;
  ::uint32_t plat() const;
  void set_plat(::uint32_t value);

  private:
  ::uint32_t _internal_plat() const;
  void _internal_set_plat(::uint32_t value);

  public:
  // optional uint32 login_success = 5;
  bool has_login_success() const;
  void clear_login_success() ;
  ::uint32_t login_success() const;
  void set_login_success(::uint32_t value);

  private:
  ::uint32_t _internal_login_success() const;
  void _internal_set_login_success(::uint32_t value);

  public:
  // optional uint32 nsid = 6;
  bool has_nsid() const;
  void clear_nsid() ;
  ::uint32_t nsid() const;
  void set_nsid(::uint32_t value);

  private:
  ::uint32_t _internal_nsid() const;
  void _internal_set_nsid(::uint32_t value);

  public:
  // optional .GCToBS.MsgNum msgnum = 1 [default = eMsgToBSFromGC_OneClinetLogin];
  bool has_msgnum() const;
  void clear_msgnum() ;
  ::GCToBS::MsgNum msgnum() const;
  void set_msgnum(::GCToBS::MsgNum value);

  private:
  ::GCToBS::MsgNum _internal_msgnum() const;
  void _internal_set_msgnum(::GCToBS::MsgNum value);

  public:
  // @@protoc_insertion_point(class_scope:GCToBS.OneClinetLogin)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 1,
      42, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uin_;
    ::google::protobuf::internal::ArenaStringPtr sessionid_;
    ::uint32_t plat_;
    ::uint32_t login_success_;
    ::uint32_t nsid_;
    int msgnum_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GCToBS_2eproto;
};
// -------------------------------------------------------------------

class AskGateAddress final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GCToBS.AskGateAddress) */ {
 public:
  inline AskGateAddress() : AskGateAddress(nullptr) {}
  ~AskGateAddress() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AskGateAddress(
      ::google::protobuf::internal::ConstantInitialized);

  inline AskGateAddress(const AskGateAddress& from) : AskGateAddress(nullptr, from) {}
  inline AskGateAddress(AskGateAddress&& from) noexcept
      : AskGateAddress(nullptr, std::move(from)) {}
  inline AskGateAddress& operator=(const AskGateAddress& from) {
    CopyFrom(from);
    return *this;
  }
  inline AskGateAddress& operator=(AskGateAddress&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AskGateAddress& default_instance() {
    return *internal_default_instance();
  }
  static inline const AskGateAddress* internal_default_instance() {
    return reinterpret_cast<const AskGateAddress*>(
        &_AskGateAddress_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AskGateAddress& a, AskGateAddress& b) { a.Swap(&b); }
  inline void Swap(AskGateAddress* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AskGateAddress* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AskGateAddress* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AskGateAddress>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AskGateAddress& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AskGateAddress& from) { AskGateAddress::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AskGateAddress* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "GCToBS.AskGateAddress"; }

 protected:
  explicit AskGateAddress(::google::protobuf::Arena* arena);
  AskGateAddress(::google::protobuf::Arena* arena, const AskGateAddress& from);
  AskGateAddress(::google::protobuf::Arena* arena, AskGateAddress&& from) noexcept
      : AskGateAddress(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUsernameFieldNumber = 3,
    kTokenFieldNumber = 4,
    kPlatFieldNumber = 2,
    kMsgnumFieldNumber = 1,
  };
  // optional string username = 3;
  bool has_username() const;
  void clear_username() ;
  const std::string& username() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_username(Arg_&& arg, Args_... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* value);

  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(
      const std::string& value);
  std::string* _internal_mutable_username();

  public:
  // optional string token = 4;
  bool has_token() const;
  void clear_token() ;
  const std::string& token() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_token(Arg_&& arg, Args_... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* value);

  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(
      const std::string& value);
  std::string* _internal_mutable_token();

  public:
  // optional int32 plat = 2;
  bool has_plat() const;
  void clear_plat() ;
  ::int32_t plat() const;
  void set_plat(::int32_t value);

  private:
  ::int32_t _internal_plat() const;
  void _internal_set_plat(::int32_t value);

  public:
  // optional .GCToBS.MsgNum msgnum = 1 [default = eMsgToBSFromGC_AskGateAddress];
  bool has_msgnum() const;
  void clear_msgnum() ;
  ::GCToBS::MsgNum msgnum() const;
  void set_msgnum(::GCToBS::MsgNum value);

  private:
  ::GCToBS::MsgNum _internal_msgnum() const;
  void _internal_set_msgnum(::GCToBS::MsgNum value);

  public:
  // @@protoc_insertion_point(class_scope:GCToBS.AskGateAddress)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 1,
      43, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr username_;
    ::google::protobuf::internal::ArenaStringPtr token_;
    ::int32_t plat_;
    int msgnum_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GCToBS_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AskGateAddress

// optional .GCToBS.MsgNum msgnum = 1 [default = eMsgToBSFromGC_AskGateAddress];
inline bool AskGateAddress::has_msgnum() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void AskGateAddress::clear_msgnum() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.msgnum_ = 32769;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::GCToBS::MsgNum AskGateAddress::msgnum() const {
  // @@protoc_insertion_point(field_get:GCToBS.AskGateAddress.msgnum)
  return _internal_msgnum();
}
inline void AskGateAddress::set_msgnum(::GCToBS::MsgNum value) {
  _internal_set_msgnum(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:GCToBS.AskGateAddress.msgnum)
}
inline ::GCToBS::MsgNum AskGateAddress::_internal_msgnum() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::GCToBS::MsgNum>(_impl_.msgnum_);
}
inline void AskGateAddress::_internal_set_msgnum(::GCToBS::MsgNum value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  assert(::GCToBS::MsgNum_IsValid(value));
  _impl_.msgnum_ = value;
}

// optional int32 plat = 2;
inline bool AskGateAddress::has_plat() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void AskGateAddress::clear_plat() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.plat_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t AskGateAddress::plat() const {
  // @@protoc_insertion_point(field_get:GCToBS.AskGateAddress.plat)
  return _internal_plat();
}
inline void AskGateAddress::set_plat(::int32_t value) {
  _internal_set_plat(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:GCToBS.AskGateAddress.plat)
}
inline ::int32_t AskGateAddress::_internal_plat() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.plat_;
}
inline void AskGateAddress::_internal_set_plat(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.plat_ = value;
}

// optional string username = 3;
inline bool AskGateAddress::has_username() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void AskGateAddress::clear_username() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.username_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AskGateAddress::username() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GCToBS.AskGateAddress.username)
  return _internal_username();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AskGateAddress::set_username(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.username_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GCToBS.AskGateAddress.username)
}
inline std::string* AskGateAddress::mutable_username() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:GCToBS.AskGateAddress.username)
  return _s;
}
inline const std::string& AskGateAddress::_internal_username() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.username_.Get();
}
inline void AskGateAddress::_internal_set_username(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.username_.Set(value, GetArena());
}
inline std::string* AskGateAddress::_internal_mutable_username() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.username_.Mutable( GetArena());
}
inline std::string* AskGateAddress::release_username() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:GCToBS.AskGateAddress.username)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.username_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.username_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void AskGateAddress::set_allocated_username(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.username_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.username_.IsDefault()) {
          _impl_.username_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:GCToBS.AskGateAddress.username)
}

// optional string token = 4;
inline bool AskGateAddress::has_token() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void AskGateAddress::clear_token() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.token_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& AskGateAddress::token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GCToBS.AskGateAddress.token)
  return _internal_token();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AskGateAddress::set_token(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GCToBS.AskGateAddress.token)
}
inline std::string* AskGateAddress::mutable_token() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:GCToBS.AskGateAddress.token)
  return _s;
}
inline const std::string& AskGateAddress::_internal_token() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.token_.Get();
}
inline void AskGateAddress::_internal_set_token(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.token_.Set(value, GetArena());
}
inline std::string* AskGateAddress::_internal_mutable_token() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.token_.Mutable( GetArena());
}
inline std::string* AskGateAddress::release_token() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:GCToBS.AskGateAddress.token)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.token_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.token_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void AskGateAddress::set_allocated_token(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.token_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.token_.IsDefault()) {
          _impl_.token_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:GCToBS.AskGateAddress.token)
}

// -------------------------------------------------------------------

// OneClinetLogin

// optional .GCToBS.MsgNum msgnum = 1 [default = eMsgToBSFromGC_OneClinetLogin];
inline bool OneClinetLogin::has_msgnum() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void OneClinetLogin::clear_msgnum() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.msgnum_ = 32770;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::GCToBS::MsgNum OneClinetLogin::msgnum() const {
  // @@protoc_insertion_point(field_get:GCToBS.OneClinetLogin.msgnum)
  return _internal_msgnum();
}
inline void OneClinetLogin::set_msgnum(::GCToBS::MsgNum value) {
  _internal_set_msgnum(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:GCToBS.OneClinetLogin.msgnum)
}
inline ::GCToBS::MsgNum OneClinetLogin::_internal_msgnum() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::GCToBS::MsgNum>(_impl_.msgnum_);
}
inline void OneClinetLogin::_internal_set_msgnum(::GCToBS::MsgNum value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  assert(::GCToBS::MsgNum_IsValid(value));
  _impl_.msgnum_ = value;
}

// optional string uin = 2;
inline bool OneClinetLogin::has_uin() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void OneClinetLogin::clear_uin() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uin_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& OneClinetLogin::uin() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GCToBS.OneClinetLogin.uin)
  return _internal_uin();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OneClinetLogin::set_uin(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.uin_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GCToBS.OneClinetLogin.uin)
}
inline std::string* OneClinetLogin::mutable_uin() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uin();
  // @@protoc_insertion_point(field_mutable:GCToBS.OneClinetLogin.uin)
  return _s;
}
inline const std::string& OneClinetLogin::_internal_uin() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.uin_.Get();
}
inline void OneClinetLogin::_internal_set_uin(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.uin_.Set(value, GetArena());
}
inline std::string* OneClinetLogin::_internal_mutable_uin() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.uin_.Mutable( GetArena());
}
inline std::string* OneClinetLogin::release_uin() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:GCToBS.OneClinetLogin.uin)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.uin_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.uin_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OneClinetLogin::set_allocated_uin(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.uin_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.uin_.IsDefault()) {
          _impl_.uin_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:GCToBS.OneClinetLogin.uin)
}

// optional string sessionid = 3;
inline bool OneClinetLogin::has_sessionid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void OneClinetLogin::clear_sessionid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sessionid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& OneClinetLogin::sessionid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GCToBS.OneClinetLogin.sessionid)
  return _internal_sessionid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OneClinetLogin::set_sessionid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.sessionid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GCToBS.OneClinetLogin.sessionid)
}
inline std::string* OneClinetLogin::mutable_sessionid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sessionid();
  // @@protoc_insertion_point(field_mutable:GCToBS.OneClinetLogin.sessionid)
  return _s;
}
inline const std::string& OneClinetLogin::_internal_sessionid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.sessionid_.Get();
}
inline void OneClinetLogin::_internal_set_sessionid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.sessionid_.Set(value, GetArena());
}
inline std::string* OneClinetLogin::_internal_mutable_sessionid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.sessionid_.Mutable( GetArena());
}
inline std::string* OneClinetLogin::release_sessionid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:GCToBS.OneClinetLogin.sessionid)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.sessionid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sessionid_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OneClinetLogin::set_allocated_sessionid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.sessionid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sessionid_.IsDefault()) {
          _impl_.sessionid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:GCToBS.OneClinetLogin.sessionid)
}

// optional uint32 plat = 4;
inline bool OneClinetLogin::has_plat() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void OneClinetLogin::clear_plat() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.plat_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t OneClinetLogin::plat() const {
  // @@protoc_insertion_point(field_get:GCToBS.OneClinetLogin.plat)
  return _internal_plat();
}
inline void OneClinetLogin::set_plat(::uint32_t value) {
  _internal_set_plat(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:GCToBS.OneClinetLogin.plat)
}
inline ::uint32_t OneClinetLogin::_internal_plat() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.plat_;
}
inline void OneClinetLogin::_internal_set_plat(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.plat_ = value;
}

// optional uint32 login_success = 5;
inline bool OneClinetLogin::has_login_success() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void OneClinetLogin::clear_login_success() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.login_success_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::uint32_t OneClinetLogin::login_success() const {
  // @@protoc_insertion_point(field_get:GCToBS.OneClinetLogin.login_success)
  return _internal_login_success();
}
inline void OneClinetLogin::set_login_success(::uint32_t value) {
  _internal_set_login_success(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:GCToBS.OneClinetLogin.login_success)
}
inline ::uint32_t OneClinetLogin::_internal_login_success() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.login_success_;
}
inline void OneClinetLogin::_internal_set_login_success(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.login_success_ = value;
}

// optional uint32 nsid = 6;
inline bool OneClinetLogin::has_nsid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void OneClinetLogin::clear_nsid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.nsid_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::uint32_t OneClinetLogin::nsid() const {
  // @@protoc_insertion_point(field_get:GCToBS.OneClinetLogin.nsid)
  return _internal_nsid();
}
inline void OneClinetLogin::set_nsid(::uint32_t value) {
  _internal_set_nsid(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:GCToBS.OneClinetLogin.nsid)
}
inline ::uint32_t OneClinetLogin::_internal_nsid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.nsid_;
}
inline void OneClinetLogin::_internal_set_nsid(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.nsid_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace GCToBS


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::GCToBS::MsgNum> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::GCToBS::MsgNum>() {
  return ::GCToBS::MsgNum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_GCToBS_2eproto_2epb_2eh
