// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GSToCS.proto
// Protobuf C++ Version: 4.26.0-dev

#include "GSToCS.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GSToCS {

inline constexpr UserOffLine::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        usernetid_{0},
        mgsid_{static_cast< ::GSToCS::MsgID >(8197)} {}

template <typename>
PROTOBUF_CONSTEXPR UserOffLine::UserOffLine(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UserOffLineDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserOffLineDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserOffLineDefaultTypeInternal() {}
  union {
    UserOffLine _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserOffLineDefaultTypeInternal _UserOffLine_default_instance_;

inline constexpr ReportGetSomeMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        otherval_{::uint64_t{0u}},
        gotmsgid_{0},
        mgsid_{static_cast< ::GSToCS::MsgID >(8196)} {}

template <typename>
PROTOBUF_CONSTEXPR ReportGetSomeMsg::ReportGetSomeMsg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ReportGetSomeMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReportGetSomeMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReportGetSomeMsgDefaultTypeInternal() {}
  union {
    ReportGetSomeMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReportGetSomeMsgDefaultTypeInternal _ReportGetSomeMsg_default_instance_;

inline constexpr ReportGCMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        othermsg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        nsid_{0},
        othermsgid_{0},
        msgid_{static_cast< ::GSToCS::MsgID >(8195)} {}

template <typename>
PROTOBUF_CONSTEXPR ReportGCMsg::ReportGCMsg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ReportGCMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReportGCMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReportGCMsgDefaultTypeInternal() {}
  union {
    ReportGCMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReportGCMsgDefaultTypeInternal _ReportGCMsg_default_instance_;

inline constexpr Asking::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        time_{::int64_t{0}},
        mgsid_{static_cast< ::GSToCS::MsgID >(8193)} {}

template <typename>
PROTOBUF_CONSTEXPR Asking::Asking(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AskingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AskingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AskingDefaultTypeInternal() {}
  union {
    Asking _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AskingDefaultTypeInternal _Asking_default_instance_;

inline constexpr AskRegiste::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        usepwd_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        gsid_{0},
        port_{0},
        msgid_{static_cast< ::GSToCS::MsgID >(8194)} {}

template <typename>
PROTOBUF_CONSTEXPR AskRegiste::AskRegiste(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AskRegisteDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AskRegisteDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AskRegisteDefaultTypeInternal() {}
  union {
    AskRegiste _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AskRegisteDefaultTypeInternal _AskRegiste_default_instance_;
}  // namespace GSToCS
static ::_pb::Metadata file_level_metadata_GSToCS_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_GSToCS_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_GSToCS_2eproto = nullptr;
const ::uint32_t
    TableStruct_GSToCS_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::GSToCS::UserOffLine, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::UserOffLine, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GSToCS::UserOffLine, _impl_.mgsid_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::UserOffLine, _impl_.usernetid_),
        1,
        0,
        PROTOBUF_FIELD_OFFSET(::GSToCS::Asking, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::Asking, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GSToCS::Asking, _impl_.mgsid_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::Asking, _impl_.time_),
        1,
        0,
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGetSomeMsg, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGetSomeMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGetSomeMsg, _impl_.mgsid_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGetSomeMsg, _impl_.gotmsgid_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGetSomeMsg, _impl_.otherval_),
        2,
        1,
        0,
        PROTOBUF_FIELD_OFFSET(::GSToCS::AskRegiste, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::AskRegiste, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GSToCS::AskRegiste, _impl_.msgid_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::AskRegiste, _impl_.gsid_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::AskRegiste, _impl_.ip_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::AskRegiste, _impl_.port_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::AskRegiste, _impl_.usepwd_),
        4,
        2,
        0,
        3,
        1,
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGCMsg, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGCMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGCMsg, _impl_.msgid_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGCMsg, _impl_.nsid_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGCMsg, _impl_.othermsgid_),
        PROTOBUF_FIELD_OFFSET(::GSToCS::ReportGCMsg, _impl_.othermsg_),
        3,
        1,
        2,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::GSToCS::UserOffLine)},
        {12, 22, -1, sizeof(::GSToCS::Asking)},
        {24, 35, -1, sizeof(::GSToCS::ReportGetSomeMsg)},
        {38, 51, -1, sizeof(::GSToCS::AskRegiste)},
        {56, 68, -1, sizeof(::GSToCS::ReportGCMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::GSToCS::_UserOffLine_default_instance_._instance,
    &::GSToCS::_Asking_default_instance_._instance,
    &::GSToCS::_ReportGetSomeMsg_default_instance_._instance,
    &::GSToCS::_AskRegiste_default_instance_._instance,
    &::GSToCS::_ReportGCMsg_default_instance_._instance,
};
const char descriptor_table_protodef_GSToCS_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014GSToCS.proto\022\006GSToCS\"Z\n\013UserOffLine\0228\n"
    "\005mgsid\030\001 \001(\0162\r.GSToCS.MsgID:\032eMsgToCSFro"
    "mGS_UserOffLine\022\021\n\tusernetid\030\002 \001(\005\"L\n\006As"
    "king\0224\n\005mgsid\030\001 \001(\0162\r.GSToCS.MsgID:\026eMsg"
    "ToCSFromGS_AskPing\022\014\n\004time\030\002 \001(\003\"u\n\020Repo"
    "rtGetSomeMsg\022=\n\005mgsid\030\001 \001(\0162\r.GSToCS.Msg"
    "ID:\037eMsgToCSFromGS_ReportGetSomeMsg\022\020\n\010g"
    "otmsgid\030\002 \001(\005\022\020\n\010otherval\030\003 \001(\004\"}\n\nAskRe"
    "giste\0227\n\005msgid\030\001 \001(\0162\r.GSToCS.MsgID:\031eMs"
    "gToCSFromGS_AskRegiste\022\014\n\004gsid\030\002 \001(\005\022\n\n\002"
    "ip\030\003 \001(\t\022\014\n\004port\030\004 \001(\005\022\016\n\006usepwd\030\005 \001(\t\"{"
    "\n\013ReportGCMsg\0228\n\005msgid\030\001 \001(\0162\r.GSToCS.Ms"
    "gID:\032eMsgToCSFromGS_ReportGCMsg\022\014\n\004nsid\030"
    "\002 \001(\005\022\022\n\nothermsgid\030\003 \001(\005\022\020\n\010othermsg\030\004 "
    "\001(\014*\340\001\n\005MsgID\022\031\n\024eMsgToCSFromGS_Begin\020\200@"
    "\022\033\n\026eMsgToCSFromGS_AskPing\020\201@\022\036\n\031eMsgToC"
    "SFromGS_AskRegiste\020\202@\022\037\n\032eMsgToCSFromGS_"
    "ReportGCMsg\020\203@\022$\n\037eMsgToCSFromGS_ReportG"
    "etSomeMsg\020\204@\022\037\n\032eMsgToCSFromGS_UserOffLi"
    "ne\020\205@\022\027\n\022eMsgToCSFromGS_End\020\210@"
};
static ::absl::once_flag descriptor_table_GSToCS_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_GSToCS_2eproto = {
    false,
    false,
    790,
    descriptor_table_protodef_GSToCS_2eproto,
    "GSToCS.proto",
    &descriptor_table_GSToCS_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_GSToCS_2eproto::offsets,
    file_level_metadata_GSToCS_2eproto,
    file_level_enum_descriptors_GSToCS_2eproto,
    file_level_service_descriptors_GSToCS_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_GSToCS_2eproto_getter() {
  return &descriptor_table_GSToCS_2eproto;
}
namespace GSToCS {
const ::google::protobuf::EnumDescriptor* MsgID_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_GSToCS_2eproto);
  return file_level_enum_descriptors_GSToCS_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MsgID_internal_data_[] = {
    401408u, 32u, 4u, };
bool MsgID_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, MsgID_internal_data_);
}
// ===================================================================

class UserOffLine::_Internal {
 public:
  using HasBits = decltype(std::declval<UserOffLine>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(UserOffLine, _impl_._has_bits_);
};

UserOffLine::UserOffLine(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GSToCS.UserOffLine)
}
UserOffLine::UserOffLine(
    ::google::protobuf::Arena* arena, const UserOffLine& from)
    : UserOffLine(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE UserOffLine::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        mgsid_{static_cast< ::GSToCS::MsgID >(8197)} {}

inline void UserOffLine::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.usernetid_ = {};
}
UserOffLine::~UserOffLine() {
  // @@protoc_insertion_point(destructor:GSToCS.UserOffLine)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UserOffLine::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
UserOffLine::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(UserOffLine, _impl_._cached_size_),
              false,
          },
          &UserOffLine::MergeImpl,
          &UserOffLine::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void UserOffLine::Clear() {
// @@protoc_insertion_point(message_clear_start:GSToCS.UserOffLine)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    _impl_.usernetid_ = 0;
    _impl_.mgsid_ = 8197;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UserOffLine::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> UserOffLine::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UserOffLine, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_UserOffLine_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GSToCS::UserOffLine>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 usernetid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserOffLine, _impl_.usernetid_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(UserOffLine, _impl_.usernetid_)}},
    // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_UserOffLine];
    {::_pbi::TcParser::FastEvS1,
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(UserOffLine, _impl_.mgsid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_UserOffLine];
    {PROTOBUF_FIELD_OFFSET(UserOffLine, _impl_.mgsid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
    // optional int32 usernetid = 2;
    {PROTOBUF_FIELD_OFFSET(UserOffLine, _impl_.usernetid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }}, {{
    {::_pbi::FieldAuxEnumData{}, ::GSToCS::MsgID_internal_data_},
  }}, {{
  }},
};

::uint8_t* UserOffLine::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GSToCS.UserOffLine)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_UserOffLine];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_mgsid(), target);
  }

  // optional int32 usernetid = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_usernetid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GSToCS.UserOffLine)
  return target;
}

::size_t UserOffLine::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GSToCS.UserOffLine)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int32 usernetid = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_usernetid());
    }

    // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_UserOffLine];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_mgsid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void UserOffLine::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserOffLine*>(&to_msg);
  auto& from = static_cast<const UserOffLine&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GSToCS.UserOffLine)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.usernetid_ = from._impl_.usernetid_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.mgsid_ = from._impl_.mgsid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserOffLine::CopyFrom(const UserOffLine& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GSToCS.UserOffLine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UserOffLine::IsInitialized() const {
  return true;
}

void UserOffLine::InternalSwap(UserOffLine* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UserOffLine, _impl_.mgsid_)
      + sizeof(UserOffLine::_impl_.mgsid_)
      - PROTOBUF_FIELD_OFFSET(UserOffLine, _impl_.usernetid_)>(
          reinterpret_cast<char*>(&_impl_.usernetid_),
          reinterpret_cast<char*>(&other->_impl_.usernetid_));
}

::google::protobuf::Metadata UserOffLine::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_GSToCS_2eproto_getter,
                                   &descriptor_table_GSToCS_2eproto_once,
                                   file_level_metadata_GSToCS_2eproto[0]);
}
// ===================================================================

class Asking::_Internal {
 public:
  using HasBits = decltype(std::declval<Asking>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Asking, _impl_._has_bits_);
};

Asking::Asking(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GSToCS.Asking)
}
Asking::Asking(
    ::google::protobuf::Arena* arena, const Asking& from)
    : Asking(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Asking::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        mgsid_{static_cast< ::GSToCS::MsgID >(8193)} {}

inline void Asking::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.time_ = {};
}
Asking::~Asking() {
  // @@protoc_insertion_point(destructor:GSToCS.Asking)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Asking::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Asking::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Asking, _impl_._cached_size_),
              false,
          },
          &Asking::MergeImpl,
          &Asking::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void Asking::Clear() {
// @@protoc_insertion_point(message_clear_start:GSToCS.Asking)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    _impl_.time_ = ::int64_t{0};
    _impl_.mgsid_ = 8193;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Asking::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> Asking::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Asking, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Asking_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GSToCS::Asking>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int64 time = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Asking, _impl_.time_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(Asking, _impl_.time_)}},
    // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_AskPing];
    {::_pbi::TcParser::FastEvS1,
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(Asking, _impl_.mgsid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_AskPing];
    {PROTOBUF_FIELD_OFFSET(Asking, _impl_.mgsid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
    // optional int64 time = 2;
    {PROTOBUF_FIELD_OFFSET(Asking, _impl_.time_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }}, {{
    {::_pbi::FieldAuxEnumData{}, ::GSToCS::MsgID_internal_data_},
  }}, {{
  }},
};

::uint8_t* Asking::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GSToCS.Asking)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_AskPing];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_mgsid(), target);
  }

  // optional int64 time = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GSToCS.Asking)
  return target;
}

::size_t Asking::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GSToCS.Asking)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int64 time = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_time());
    }

    // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_AskPing];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_mgsid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Asking::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Asking*>(&to_msg);
  auto& from = static_cast<const Asking&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GSToCS.Asking)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.time_ = from._impl_.time_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.mgsid_ = from._impl_.mgsid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Asking::CopyFrom(const Asking& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GSToCS.Asking)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Asking::IsInitialized() const {
  return true;
}

void Asking::InternalSwap(Asking* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Asking, _impl_.mgsid_)
      + sizeof(Asking::_impl_.mgsid_)
      - PROTOBUF_FIELD_OFFSET(Asking, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
}

::google::protobuf::Metadata Asking::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_GSToCS_2eproto_getter,
                                   &descriptor_table_GSToCS_2eproto_once,
                                   file_level_metadata_GSToCS_2eproto[1]);
}
// ===================================================================

class ReportGetSomeMsg::_Internal {
 public:
  using HasBits = decltype(std::declval<ReportGetSomeMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_._has_bits_);
};

ReportGetSomeMsg::ReportGetSomeMsg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GSToCS.ReportGetSomeMsg)
}
ReportGetSomeMsg::ReportGetSomeMsg(
    ::google::protobuf::Arena* arena, const ReportGetSomeMsg& from)
    : ReportGetSomeMsg(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ReportGetSomeMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        mgsid_{static_cast< ::GSToCS::MsgID >(8196)} {}

inline void ReportGetSomeMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, otherval_),
           0,
           offsetof(Impl_, gotmsgid_) -
               offsetof(Impl_, otherval_) +
               sizeof(Impl_::gotmsgid_));
}
ReportGetSomeMsg::~ReportGetSomeMsg() {
  // @@protoc_insertion_point(destructor:GSToCS.ReportGetSomeMsg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ReportGetSomeMsg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ReportGetSomeMsg::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_._cached_size_),
              false,
          },
          &ReportGetSomeMsg::MergeImpl,
          &ReportGetSomeMsg::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void ReportGetSomeMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:GSToCS.ReportGetSomeMsg)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.otherval_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.gotmsgid_) -
        reinterpret_cast<char*>(&_impl_.otherval_)) + sizeof(_impl_.gotmsgid_));
    _impl_.mgsid_ = 8196;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ReportGetSomeMsg::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> ReportGetSomeMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ReportGetSomeMsg_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GSToCS::ReportGetSomeMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_ReportGetSomeMsg];
    {::_pbi::TcParser::FastEvS1,
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_.mgsid_)}},
    // optional int32 gotmsgid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReportGetSomeMsg, _impl_.gotmsgid_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_.gotmsgid_)}},
    // optional uint64 otherval = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ReportGetSomeMsg, _impl_.otherval_), 0>(),
     {24, 0, 0, PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_.otherval_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_ReportGetSomeMsg];
    {PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_.mgsid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
    // optional int32 gotmsgid = 2;
    {PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_.gotmsgid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional uint64 otherval = 3;
    {PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_.otherval_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }}, {{
    {::_pbi::FieldAuxEnumData{}, ::GSToCS::MsgID_internal_data_},
  }}, {{
  }},
};

::uint8_t* ReportGetSomeMsg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GSToCS.ReportGetSomeMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_ReportGetSomeMsg];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_mgsid(), target);
  }

  // optional int32 gotmsgid = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_gotmsgid(), target);
  }

  // optional uint64 otherval = 3;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_otherval(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GSToCS.ReportGetSomeMsg)
  return target;
}

::size_t ReportGetSomeMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GSToCS.ReportGetSomeMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional uint64 otherval = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_otherval());
    }

    // optional int32 gotmsgid = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_gotmsgid());
    }

    // optional .GSToCS.MsgID mgsid = 1 [default = eMsgToCSFromGS_ReportGetSomeMsg];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_mgsid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ReportGetSomeMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReportGetSomeMsg*>(&to_msg);
  auto& from = static_cast<const ReportGetSomeMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GSToCS.ReportGetSomeMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.otherval_ = from._impl_.otherval_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.gotmsgid_ = from._impl_.gotmsgid_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.mgsid_ = from._impl_.mgsid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReportGetSomeMsg::CopyFrom(const ReportGetSomeMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GSToCS.ReportGetSomeMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ReportGetSomeMsg::IsInitialized() const {
  return true;
}

void ReportGetSomeMsg::InternalSwap(ReportGetSomeMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_.mgsid_)
      + sizeof(ReportGetSomeMsg::_impl_.mgsid_)
      - PROTOBUF_FIELD_OFFSET(ReportGetSomeMsg, _impl_.otherval_)>(
          reinterpret_cast<char*>(&_impl_.otherval_),
          reinterpret_cast<char*>(&other->_impl_.otherval_));
}

::google::protobuf::Metadata ReportGetSomeMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_GSToCS_2eproto_getter,
                                   &descriptor_table_GSToCS_2eproto_once,
                                   file_level_metadata_GSToCS_2eproto[2]);
}
// ===================================================================

class AskRegiste::_Internal {
 public:
  using HasBits = decltype(std::declval<AskRegiste>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_._has_bits_);
};

AskRegiste::AskRegiste(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GSToCS.AskRegiste)
}
inline PROTOBUF_NDEBUG_INLINE AskRegiste::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ip_(arena, from.ip_),
        usepwd_(arena, from.usepwd_) {}

AskRegiste::AskRegiste(
    ::google::protobuf::Arena* arena,
    const AskRegiste& from)
    : ::google::protobuf::Message(arena) {
  AskRegiste* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, gsid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, gsid_),
           offsetof(Impl_, msgid_) -
               offsetof(Impl_, gsid_) +
               sizeof(Impl_::msgid_));

  // @@protoc_insertion_point(copy_constructor:GSToCS.AskRegiste)
}
inline PROTOBUF_NDEBUG_INLINE AskRegiste::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        ip_(arena),
        usepwd_(arena),
        msgid_{static_cast< ::GSToCS::MsgID >(8194)} {}

inline void AskRegiste::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, gsid_),
           0,
           offsetof(Impl_, port_) -
               offsetof(Impl_, gsid_) +
               sizeof(Impl_::port_));
}
AskRegiste::~AskRegiste() {
  // @@protoc_insertion_point(destructor:GSToCS.AskRegiste)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AskRegiste::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.ip_.Destroy();
  _impl_.usepwd_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AskRegiste::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_._cached_size_),
              false,
          },
          &AskRegiste::MergeImpl,
          &AskRegiste::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void AskRegiste::Clear() {
// @@protoc_insertion_point(message_clear_start:GSToCS.AskRegiste)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.ip_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.usepwd_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000001cu) {
    ::memset(&_impl_.gsid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.port_) -
        reinterpret_cast<char*>(&_impl_.gsid_)) + sizeof(_impl_.port_));
    _impl_.msgid_ = 8194;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AskRegiste::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 34, 2> AskRegiste::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AskRegiste_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GSToCS::AskRegiste>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional .GSToCS.MsgID msgid = 1 [default = eMsgToCSFromGS_AskRegiste];
    {::_pbi::TcParser::FastEvS1,
     {8, 4, 0, PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.msgid_)}},
    // optional int32 gsid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AskRegiste, _impl_.gsid_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.gsid_)}},
    // optional string ip = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.ip_)}},
    // optional int32 port = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AskRegiste, _impl_.port_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.port_)}},
    // optional string usepwd = 5;
    {::_pbi::TcParser::FastSS1,
     {42, 1, 0, PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.usepwd_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .GSToCS.MsgID msgid = 1 [default = eMsgToCSFromGS_AskRegiste];
    {PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.msgid_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
    // optional int32 gsid = 2;
    {PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.gsid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string ip = 3;
    {PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.ip_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int32 port = 4;
    {PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.port_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string usepwd = 5;
    {PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.usepwd_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::FieldAuxEnumData{}, ::GSToCS::MsgID_internal_data_},
  }}, {{
    "\21\0\0\2\0\6\0\0"
    "GSToCS.AskRegiste"
    "ip"
    "usepwd"
  }},
};

::uint8_t* AskRegiste::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GSToCS.AskRegiste)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .GSToCS.MsgID msgid = 1 [default = eMsgToCSFromGS_AskRegiste];
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_msgid(), target);
  }

  // optional int32 gsid = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_gsid(), target);
  }

  // optional string ip = 3;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_ip();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "GSToCS.AskRegiste.ip");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional int32 port = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_port(), target);
  }

  // optional string usepwd = 5;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_usepwd();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "GSToCS.AskRegiste.usepwd");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GSToCS.AskRegiste)
  return target;
}

::size_t AskRegiste::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GSToCS.AskRegiste)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional string ip = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_ip());
    }

    // optional string usepwd = 5;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_usepwd());
    }

    // optional int32 gsid = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_gsid());
    }

    // optional int32 port = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_port());
    }

    // optional .GSToCS.MsgID msgid = 1 [default = eMsgToCSFromGS_AskRegiste];
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_msgid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AskRegiste::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AskRegiste*>(&to_msg);
  auto& from = static_cast<const AskRegiste&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GSToCS.AskRegiste)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_ip(from._internal_ip());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_usepwd(from._internal_usepwd());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.gsid_ = from._impl_.gsid_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.port_ = from._impl_.port_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.msgid_ = from._impl_.msgid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AskRegiste::CopyFrom(const AskRegiste& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GSToCS.AskRegiste)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AskRegiste::IsInitialized() const {
  return true;
}

void AskRegiste::InternalSwap(AskRegiste* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_, &other->_impl_.ip_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.usepwd_, &other->_impl_.usepwd_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.msgid_)
      + sizeof(AskRegiste::_impl_.msgid_)
      - PROTOBUF_FIELD_OFFSET(AskRegiste, _impl_.gsid_)>(
          reinterpret_cast<char*>(&_impl_.gsid_),
          reinterpret_cast<char*>(&other->_impl_.gsid_));
}

::google::protobuf::Metadata AskRegiste::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_GSToCS_2eproto_getter,
                                   &descriptor_table_GSToCS_2eproto_once,
                                   file_level_metadata_GSToCS_2eproto[3]);
}
// ===================================================================

class ReportGCMsg::_Internal {
 public:
  using HasBits = decltype(std::declval<ReportGCMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_._has_bits_);
};

ReportGCMsg::ReportGCMsg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GSToCS.ReportGCMsg)
}
inline PROTOBUF_NDEBUG_INLINE ReportGCMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        othermsg_(arena, from.othermsg_) {}

ReportGCMsg::ReportGCMsg(
    ::google::protobuf::Arena* arena,
    const ReportGCMsg& from)
    : ::google::protobuf::Message(arena) {
  ReportGCMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, nsid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, nsid_),
           offsetof(Impl_, msgid_) -
               offsetof(Impl_, nsid_) +
               sizeof(Impl_::msgid_));

  // @@protoc_insertion_point(copy_constructor:GSToCS.ReportGCMsg)
}
inline PROTOBUF_NDEBUG_INLINE ReportGCMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        othermsg_(arena),
        msgid_{static_cast< ::GSToCS::MsgID >(8195)} {}

inline void ReportGCMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, nsid_),
           0,
           offsetof(Impl_, othermsgid_) -
               offsetof(Impl_, nsid_) +
               sizeof(Impl_::othermsgid_));
}
ReportGCMsg::~ReportGCMsg() {
  // @@protoc_insertion_point(destructor:GSToCS.ReportGCMsg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ReportGCMsg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.othermsg_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ReportGCMsg::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_._cached_size_),
              false,
          },
          &ReportGCMsg::MergeImpl,
          &ReportGCMsg::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void ReportGCMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:GSToCS.ReportGCMsg)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.othermsg_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000000eu) {
    ::memset(&_impl_.nsid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.othermsgid_) -
        reinterpret_cast<char*>(&_impl_.nsid_)) + sizeof(_impl_.othermsgid_));
    _impl_.msgid_ = 8195;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ReportGCMsg::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2> ReportGCMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ReportGCMsg_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GSToCS::ReportGCMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bytes othermsg = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 0, 0, PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.othermsg_)}},
    // optional .GSToCS.MsgID msgid = 1 [default = eMsgToCSFromGS_ReportGCMsg];
    {::_pbi::TcParser::FastEvS1,
     {8, 3, 0, PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.msgid_)}},
    // optional int32 nsid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReportGCMsg, _impl_.nsid_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.nsid_)}},
    // optional int32 othermsgid = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReportGCMsg, _impl_.othermsgid_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.othermsgid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .GSToCS.MsgID msgid = 1 [default = eMsgToCSFromGS_ReportGCMsg];
    {PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.msgid_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
    // optional int32 nsid = 2;
    {PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.nsid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 othermsgid = 3;
    {PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.othermsgid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional bytes othermsg = 4;
    {PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.othermsg_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::FieldAuxEnumData{}, ::GSToCS::MsgID_internal_data_},
  }}, {{
  }},
};

::uint8_t* ReportGCMsg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GSToCS.ReportGCMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .GSToCS.MsgID msgid = 1 [default = eMsgToCSFromGS_ReportGCMsg];
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_msgid(), target);
  }

  // optional int32 nsid = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_nsid(), target);
  }

  // optional int32 othermsgid = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_othermsgid(), target);
  }

  // optional bytes othermsg = 4;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_othermsg();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GSToCS.ReportGCMsg)
  return target;
}

::size_t ReportGCMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GSToCS.ReportGCMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional bytes othermsg = 4;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_othermsg());
    }

    // optional int32 nsid = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_nsid());
    }

    // optional int32 othermsgid = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_othermsgid());
    }

    // optional .GSToCS.MsgID msgid = 1 [default = eMsgToCSFromGS_ReportGCMsg];
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_msgid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ReportGCMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReportGCMsg*>(&to_msg);
  auto& from = static_cast<const ReportGCMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GSToCS.ReportGCMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_othermsg(from._internal_othermsg());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.nsid_ = from._impl_.nsid_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.othermsgid_ = from._impl_.othermsgid_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.msgid_ = from._impl_.msgid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReportGCMsg::CopyFrom(const ReportGCMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GSToCS.ReportGCMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ReportGCMsg::IsInitialized() const {
  return true;
}

void ReportGCMsg::InternalSwap(ReportGCMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.othermsg_, &other->_impl_.othermsg_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.msgid_)
      + sizeof(ReportGCMsg::_impl_.msgid_)
      - PROTOBUF_FIELD_OFFSET(ReportGCMsg, _impl_.nsid_)>(
          reinterpret_cast<char*>(&_impl_.nsid_),
          reinterpret_cast<char*>(&other->_impl_.nsid_));
}

::google::protobuf::Metadata ReportGCMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_GSToCS_2eproto_getter,
                                   &descriptor_table_GSToCS_2eproto_once,
                                   file_level_metadata_GSToCS_2eproto[4]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GSToCS
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_GSToCS_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
