// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: BSToGC.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace BSToGC
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AskGateAddressRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mgsid")]
        [global::System.ComponentModel.DefaultValue(MsgID.eMsgToGCFromBSAskGateAddressRet)]
        public MsgID Mgsid
        {
            get => __pbn__Mgsid ?? MsgID.eMsgToGCFromBSAskGateAddressRet;
            set => __pbn__Mgsid = value;
        }
        public bool ShouldSerializeMgsid() => __pbn__Mgsid != null;
        public void ResetMgsid() => __pbn__Mgsid = null;
        private MsgID? __pbn__Mgsid;

        [global::ProtoBuf.ProtoMember(2, Name = @"gateclient")]
        public int Gateclient
        {
            get => __pbn__Gateclient.GetValueOrDefault();
            set => __pbn__Gateclient = value;
        }
        public bool ShouldSerializeGateclient() => __pbn__Gateclient != null;
        public void ResetGateclient() => __pbn__Gateclient = null;
        private int? __pbn__Gateclient;

        [global::ProtoBuf.ProtoMember(3, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token
        {
            get => __pbn__Token ?? "";
            set => __pbn__Token = value;
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private string __pbn__Token;

        [global::ProtoBuf.ProtoMember(4, Name = @"user_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserName
        {
            get => __pbn__UserName ?? "";
            set => __pbn__UserName = value;
        }
        public bool ShouldSerializeUserName() => __pbn__UserName != null;
        public void ResetUserName() => __pbn__UserName = null;
        private string __pbn__UserName;

        [global::ProtoBuf.ProtoMember(5, Name = @"port")]
        public int Port
        {
            get => __pbn__Port.GetValueOrDefault();
            set => __pbn__Port = value;
        }
        public bool ShouldSerializePort() => __pbn__Port != null;
        public void ResetPort() => __pbn__Port = null;
        private int? __pbn__Port;

        [global::ProtoBuf.ProtoMember(6, Name = @"ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ip
        {
            get => __pbn__Ip ?? "";
            set => __pbn__Ip = value;
        }
        public bool ShouldSerializeIp() => __pbn__Ip != null;
        public void ResetIp() => __pbn__Ip = null;
        private string __pbn__Ip;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClinetLoginCheckRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mgsid")]
        [global::System.ComponentModel.DefaultValue(MsgID.eMsgToGCFromBSOneClinetLoginCheckRet)]
        public MsgID Mgsid
        {
            get => __pbn__Mgsid ?? MsgID.eMsgToGCFromBSOneClinetLoginCheckRet;
            set => __pbn__Mgsid = value;
        }
        public bool ShouldSerializeMgsid() => __pbn__Mgsid != null;
        public void ResetMgsid() => __pbn__Mgsid = null;
        private MsgID? __pbn__Mgsid;

        [global::ProtoBuf.ProtoMember(2, Name = @"login_success")]
        public uint LoginSuccess
        {
            get => __pbn__LoginSuccess.GetValueOrDefault();
            set => __pbn__LoginSuccess = value;
        }
        public bool ShouldSerializeLoginSuccess() => __pbn__LoginSuccess != null;
        public void ResetLoginSuccess() => __pbn__LoginSuccess = null;
        private uint? __pbn__LoginSuccess;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum MsgID
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGCFromBS_AskGateAddressRet")]
        eMsgToGCFromBSAskGateAddressRet = 203,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGCFromBS_OneClinetLoginCheckRet")]
        eMsgToGCFromBSOneClinetLoginCheckRet = 204,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
