// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: GCToSS.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace GCToSS
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AskSSGuideStepComp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgid")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskGuideStepComp)]
        public MsgNum Msgid
        {
            get => __pbn__Msgid ?? MsgNum.eMsgToGSToSSFromGCAskGuideStepComp;
            set => __pbn__Msgid = value;
        }
        public bool ShouldSerializeMsgid() => __pbn__Msgid != null;
        public void ResetMsgid() => __pbn__Msgid = null;
        private MsgNum? __pbn__Msgid;

        [global::ProtoBuf.ProtoMember(3, Name = @"info")]
        public global::System.Collections.Generic.List<Taskinfo> Infoes { get; } = new global::System.Collections.Generic.List<Taskinfo>();

        [global::ProtoBuf.ProtoContract(Name = @"taskinfo")]
        public partial class Taskinfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"dtype")]
            [global::System.ComponentModel.DefaultValue(AskSSGuideStepComp.Edotype.Ecomptask)]
            public AskSSGuideStepComp.Edotype Dtype
            {
                get => __pbn__Dtype ?? AskSSGuideStepComp.Edotype.Ecomptask;
                set => __pbn__Dtype = value;
            }
            public bool ShouldSerializeDtype() => __pbn__Dtype != null;
            public void ResetDtype() => __pbn__Dtype = null;
            private AskSSGuideStepComp.Edotype? __pbn__Dtype;

            [global::ProtoBuf.ProtoMember(2, Name = @"stepid")]
            public int Stepid
            {
                get => __pbn__Stepid.GetValueOrDefault();
                set => __pbn__Stepid = value;
            }
            public bool ShouldSerializeStepid() => __pbn__Stepid != null;
            public void ResetStepid() => __pbn__Stepid = null;
            private int? __pbn__Stepid;

        }

        [global::ProtoBuf.ProtoContract(Name = @"edotype")]
        public enum Edotype
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ecomptask")]
            Ecomptask = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ebuygoods")]
            Ebuygoods = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ebornsolder")]
            Ebornsolder = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"ebornhero")]
            Ebornhero = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"nextstep")]
            Nextstep = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HerosBattleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgid")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskHerosBattleInfo)]
        public MsgNum Msgid
        {
            get => __pbn__Msgid ?? MsgNum.eMsgToGSToSSFromGCAskHerosBattleInfo;
            set => __pbn__Msgid = value;
        }
        public bool ShouldSerializeMsgid() => __pbn__Msgid != null;
        public void ResetMsgid() => __pbn__Msgid = null;
        private MsgNum? __pbn__Msgid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskHeroAttributesInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgid")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskHeroAttributesInfo)]
        public MsgNum Msgid
        {
            get => __pbn__Msgid ?? MsgNum.eMsgToGSToSSFromGCAskHeroAttributesInfo;
            set => __pbn__Msgid = value;
        }
        public bool ShouldSerializeMsgid() => __pbn__Msgid != null;
        public void ResetMsgid() => __pbn__Msgid = null;
        private MsgNum? __pbn__Msgid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskQuickBattleEnd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgid")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToSSFromGSAskQuickBattleEnd)]
        public MsgNum Msgid
        {
            get => __pbn__Msgid ?? MsgNum.eMsgToSSFromGSAskQuickBattleEnd;
            set => __pbn__Msgid = value;
        }
        public bool ShouldSerializeMsgid() => __pbn__Msgid != null;
        public void ResetMsgid() => __pbn__Msgid = null;
        private MsgNum? __pbn__Msgid;

        [global::ProtoBuf.ProtoMember(2, Name = @"other")]
        public int Other
        {
            get => __pbn__Other.GetValueOrDefault();
            set => __pbn__Other = value;
        }
        public bool ShouldSerializeOther() => __pbn__Other != null;
        public void ResetOther() => __pbn__Other = null;
        private int? __pbn__Other;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskPingSS : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskPingSS)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskPingSS;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public long Time
        {
            get => __pbn__Time.GetValueOrDefault();
            set => __pbn__Time = value;
        }
        public bool ShouldSerializeTime() => __pbn__Time != null;
        public void ResetTime() => __pbn__Time = null;
        private long? __pbn__Time;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskEnterBattle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskEnterBattle)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskEnterBattle;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2)]
        public long clientTime
        {
            get => __pbn__clientTime.GetValueOrDefault();
            set => __pbn__clientTime = value;
        }
        public bool ShouldSerializeclientTime() => __pbn__clientTime != null;
        public void ResetclientTime() => __pbn__clientTime = null;
        private long? __pbn__clientTime;

        [global::ProtoBuf.ProtoMember(3, Name = @"battleid")]
        public ulong Battleid
        {
            get => __pbn__Battleid.GetValueOrDefault();
            set => __pbn__Battleid = value;
        }
        public bool ShouldSerializeBattleid() => __pbn__Battleid != null;
        public void ResetBattleid() => __pbn__Battleid = null;
        private ulong? __pbn__Battleid;

        [global::ProtoBuf.ProtoMember(4, Name = @"obuserstate")]
        public int Obuserstate
        {
            get => __pbn__Obuserstate.GetValueOrDefault();
            set => __pbn__Obuserstate = value;
        }
        public bool ShouldSerializeObuserstate() => __pbn__Obuserstate != null;
        public void ResetObuserstate() => __pbn__Obuserstate = null;
        private int? __pbn__Obuserstate;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Dir : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X
        {
            get => __pbn__X.GetValueOrDefault();
            set => __pbn__X = value;
        }
        public bool ShouldSerializeX() => __pbn__X != null;
        public void ResetX() => __pbn__X = null;
        private float? __pbn__X;

        [global::ProtoBuf.ProtoMember(2, Name = @"z")]
        public float Z
        {
            get => __pbn__Z.GetValueOrDefault();
            set => __pbn__Z = value;
        }
        public bool ShouldSerializeZ() => __pbn__Z != null;
        public void ResetZ() => __pbn__Z = null;
        private float? __pbn__Z;

        [global::ProtoBuf.ProtoMember(3, Name = @"angle")]
        public float Angle
        {
            get => __pbn__Angle.GetValueOrDefault();
            set => __pbn__Angle = value;
        }
        public bool ShouldSerializeAngle() => __pbn__Angle != null;
        public void ResetAngle() => __pbn__Angle = null;
        private float? __pbn__Angle;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveDir : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskMoveDir)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskMoveDir;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"dir")]
        public Dir Dir { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StopMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskStopMove)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskStopMove;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuyGoods : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskBuyGoods)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskBuyGoods;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"typeid")]
        public int Typeid
        {
            get => __pbn__Typeid.GetValueOrDefault();
            set => __pbn__Typeid = value;
        }
        public bool ShouldSerializeTypeid() => __pbn__Typeid != null;
        public void ResetTypeid() => __pbn__Typeid = null;
        private int? __pbn__Typeid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UseGoods : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskUseGoods)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskUseGoods;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"goodspos")]
        public int Goodspos
        {
            get => __pbn__Goodspos.GetValueOrDefault();
            set => __pbn__Goodspos = value;
        }
        public bool ShouldSerializeGoodspos() => __pbn__Goodspos != null;
        public void ResetGoodspos() => __pbn__Goodspos = null;
        private int? __pbn__Goodspos;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SellGoods : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskSellGoods)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskSellGoods;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"goodspos")]
        public int Goodspos
        {
            get => __pbn__Goodspos.GetValueOrDefault();
            set => __pbn__Goodspos = value;
        }
        public bool ShouldSerializeGoodspos() => __pbn__Goodspos != null;
        public void ResetGoodspos() => __pbn__Goodspos = null;
        private int? __pbn__Goodspos;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveGoods : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskMoveGoods)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskMoveGoods;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"frompos")]
        public int Frompos
        {
            get => __pbn__Frompos.GetValueOrDefault();
            set => __pbn__Frompos = value;
        }
        public bool ShouldSerializeFrompos() => __pbn__Frompos != null;
        public void ResetFrompos() => __pbn__Frompos = null;
        private int? __pbn__Frompos;

        [global::ProtoBuf.ProtoMember(4, Name = @"topos")]
        public int Topos
        {
            get => __pbn__Topos.GetValueOrDefault();
            set => __pbn__Topos = value;
        }
        public bool ShouldSerializeTopos() => __pbn__Topos != null;
        public void ResetTopos() => __pbn__Topos = null;
        private int? __pbn__Topos;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportBattleLoadingState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCReportBattleLoadingState)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCReportBattleLoadingState;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"loadingnum")]
        public int Loadingnum
        {
            get => __pbn__Loadingnum.GetValueOrDefault();
            set => __pbn__Loadingnum = value;
        }
        public bool ShouldSerializeLoadingnum() => __pbn__Loadingnum != null;
        public void ResetLoadingnum() => __pbn__Loadingnum = null;
        private int? __pbn__Loadingnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UseSkill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskUseSkill)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskUseSkill;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"skillid")]
        public int Skillid
        {
            get => __pbn__Skillid.GetValueOrDefault();
            set => __pbn__Skillid = value;
        }
        public bool ShouldSerializeSkillid() => __pbn__Skillid != null;
        public void ResetSkillid() => __pbn__Skillid = null;
        private int? __pbn__Skillid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LockTar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskLockTarget)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskLockTarget;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"guid")]
        public long Guid
        {
            get => __pbn__Guid.GetValueOrDefault();
            set => __pbn__Guid = value;
        }
        public bool ShouldSerializeGuid() => __pbn__Guid != null;
        public void ResetGuid() => __pbn__Guid = null;
        private long? __pbn__Guid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportAltarStrawSolder : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCReportAltarStrawSolder)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCReportAltarStrawSolder;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public int Type
        {
            get => __pbn__Type.GetValueOrDefault();
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

        [global::ProtoBuf.ProtoMember(3, Name = @"index")]
        public int Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private int? __pbn__Index;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Absorb : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskAbsorbMonster)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskAbsorbMonster;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"removeid")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int Removeid
        {
            get => __pbn__Removeid ?? -1;
            set => __pbn__Removeid = value;
        }
        public bool ShouldSerializeRemoveid() => __pbn__Removeid != null;
        public void ResetRemoveid() => __pbn__Removeid = null;
        private int? __pbn__Removeid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GasExplosion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskGasExplosion)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskGasExplosion;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuReborn : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskBuyRebornHero)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskBuyRebornHero;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GMCmd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCGMCmd)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCGMCmd;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"cmd")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Cmd
        {
            get => __pbn__Cmd ?? "";
            set => __pbn__Cmd = value;
        }
        public bool ShouldSerializeCmd() => __pbn__Cmd != null;
        public void ResetCmd() => __pbn__Cmd = null;
        private string __pbn__Cmd;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StepID : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCStepId)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCStepId;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"stepid")]
        public int Stepid
        {
            get => __pbn__Stepid.GetValueOrDefault();
            set => __pbn__Stepid = value;
        }
        public bool ShouldSerializeStepid() => __pbn__Stepid != null;
        public void ResetStepid() => __pbn__Stepid = null;
        private int? __pbn__Stepid;

        [global::ProtoBuf.ProtoMember(4, Name = @"type")]
        public int Type
        {
            get => __pbn__Type.GetValueOrDefault();
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AutoAtk : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskAutoAttack)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskAutoAttack;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuideJumpToHall : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskGuideEndJumpToHall)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskGuideEndJumpToHall;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskReconnect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskReconnect)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskReconnect;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Pos : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X
        {
            get => __pbn__X.GetValueOrDefault();
            set => __pbn__X = value;
        }
        public bool ShouldSerializeX() => __pbn__X != null;
        public void ResetX() => __pbn__X = null;
        private float? __pbn__X;

        [global::ProtoBuf.ProtoMember(2, Name = @"z")]
        public float Z
        {
            get => __pbn__Z.GetValueOrDefault();
            set => __pbn__Z = value;
        }
        public bool ShouldSerializeZ() => __pbn__Z != null;
        public void ResetZ() => __pbn__Z = null;
        private float? __pbn__Z;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveTar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskMovePos)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskMovePos;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(3, Name = @"pos")]
        public Pos Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskBornNPC : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskBornNPC)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskBornNPC;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"stepid")]
        public int Stepid
        {
            get => __pbn__Stepid.GetValueOrDefault();
            set => __pbn__Stepid = value;
        }
        public bool ShouldSerializeStepid() => __pbn__Stepid != null;
        public void ResetStepid() => __pbn__Stepid = null;
        private int? __pbn__Stepid;

        [global::ProtoBuf.ProtoMember(3, Name = @"state")]
        public int State
        {
            get => __pbn__State.GetValueOrDefault();
            set => __pbn__State = value;
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private int? __pbn__State;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AlwaysAutoAtk : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskAlwaysAutoAtk)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskAlwaysAutoAtk;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"flag")]
        public bool Flag
        {
            get => __pbn__Flag.GetValueOrDefault();
            set => __pbn__Flag = value;
        }
        public bool ShouldSerializeFlag() => __pbn__Flag != null;
        public void ResetFlag() => __pbn__Flag = null;
        private bool? __pbn__Flag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrySeleceHero : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskTrySelectHero)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskTrySelectHero;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"heroid")]
        public uint Heroid
        {
            get => __pbn__Heroid.GetValueOrDefault();
            set => __pbn__Heroid = value;
        }
        public bool ShouldSerializeHeroid() => __pbn__Heroid != null;
        public void ResetHeroid() => __pbn__Heroid = null;
        private uint? __pbn__Heroid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SelectHero : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskSelectHero)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskSelectHero;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"heroid")]
        public int Heroid
        {
            get => __pbn__Heroid.GetValueOrDefault();
            set => __pbn__Heroid = value;
        }
        public bool ShouldSerializeHeroid() => __pbn__Heroid != null;
        public void ResetHeroid() => __pbn__Heroid = null;
        private int? __pbn__Heroid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SelectRunePage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCAskSelectRunePage)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCAskSelectRunePage;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"pageindex")]
        public int Pageindex
        {
            get => __pbn__Pageindex.GetValueOrDefault();
            set => __pbn__Pageindex = value;
        }
        public bool ShouldSerializePageindex() => __pbn__Pageindex != null;
        public void ResetPageindex() => __pbn__Pageindex = null;
        private int? __pbn__Pageindex;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoadComplete : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToSSFromGCReportLoadBattleComplete)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToSSFromGCReportLoadBattleComplete;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum MsgNum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_Begin")]
        eMsgToGSToSSFromGCBegin = 16384,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskPingSS")]
        eMsgToGSToSSFromGCAskPingSS = 16385,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskEnterBattle")]
        eMsgToGSToSSFromGCAskEnterBattle = 16386,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskMoveDir")]
        eMsgToGSToSSFromGCAskMoveDir = 16387,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskStopMove")]
        eMsgToGSToSSFromGCAskStopMove = 16388,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskBuyGoods")]
        eMsgToGSToSSFromGCAskBuyGoods = 16389,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskUseGoods")]
        eMsgToGSToSSFromGCAskUseGoods = 16390,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskSellGoods")]
        eMsgToGSToSSFromGCAskSellGoods = 16391,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskMoveGoods")]
        eMsgToGSToSSFromGCAskMoveGoods = 16392,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_ReportBattleLoadingState")]
        eMsgToGSToSSFromGCReportBattleLoadingState = 16393,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskAttack")]
        eMsgToGSToSSFromGCAskAttack = 16394,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskUseSkill")]
        eMsgToGSToSSFromGCAskUseSkill = 16395,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskLockTarget")]
        eMsgToGSToSSFromGCAskLockTarget = 16396,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_ReportAltarStrawSolder")]
        eMsgToGSToSSFromGCReportAltarStrawSolder = 16397,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskAbsorbMonster")]
        eMsgToGSToSSFromGCAskAbsorbMonster = 16398,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskCancelAbsorbSkill")]
        eMsgToGSToSSFromGCAskCancelAbsorbSkill = 16399,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskGasExplosion")]
        eMsgToGSToSSFromGCAskGasExplosion = 16400,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskBuyRebornHero")]
        eMsgToGSToSSFromGCAskBuyRebornHero = 16401,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_GMCmd")]
        eMsgToGSToSSFromGCGMCmd = 16402,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskOBBattle")]
        eMsgToGSToSSFromGCAskOBBattle = 16403,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_StepId")]
        eMsgToGSToSSFromGCStepId = 16404,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskBornNPC")]
        eMsgToGSToSSFromGCAskBornNPC = 16405,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskAutoAttack")]
        eMsgToGSToSSFromGCAskAutoAttack = 16406,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskGuideEndJumpToHall")]
        eMsgToGSToSSFromGCAskGuideEndJumpToHall = 16407,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskReconnect")]
        eMsgToGSToSSFromGCAskReconnect = 16408,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskMovePos")]
        eMsgToGSToSSFromGCAskMovePos = 16409,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskAlwaysAutoAtk")]
        eMsgToGSToSSFromGCAskAlwaysAutoAtk = 16410,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToSSFromGS_ReportSSMsg")]
        eMsgToSSFromGSReportSSMsg = 16411,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToSSFromGS_AskQuickBattleEnd")]
        eMsgToSSFromGSAskQuickBattleEnd = 16412,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskTrySelectHero")]
        eMsgToGSToSSFromGCAskTrySelectHero = 16505,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskSelectHero")]
        eMsgToGSToSSFromGCAskSelectHero = 16506,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskSelectRunePage")]
        eMsgToGSToSSFromGCAskSelectRunePage = 16507,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_ReportLoadBattleComplete")]
        eMsgToGSToSSFromGCReportLoadBattleComplete = 16520,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskHeroAttributesInfo")]
        eMsgToGSToSSFromGCAskHeroAttributesInfo = 16521,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskHerosBattleInfo")]
        eMsgToGSToSSFromGCAskHerosBattleInfo = 16522,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_AskGuideStepComp")]
        eMsgToGSToSSFromGCAskGuideStepComp = 16540,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToSSFromGC_End")]
        eMsgToGSToSSFromGCEnd = 17000,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
