// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: GCToCS.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace GCToCS
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AskOneTaskRewards : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskOneTaskRewards)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskOneTaskRewards;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"task_guid")]
        public uint TaskGuid
        {
            get => __pbn__TaskGuid.GetValueOrDefault();
            set => __pbn__TaskGuid = value;
        }
        public bool ShouldSerializeTaskGuid() => __pbn__TaskGuid != null;
        public void ResetTaskGuid() => __pbn__TaskGuid = null;
        private uint? __pbn__TaskGuid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CDKReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCCDKReq)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCCDKReq;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"cdkstr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Cdkstr
        {
            get => __pbn__Cdkstr ?? "";
            set => __pbn__Cdkstr = value;
        }
        public bool ShouldSerializeCdkstr() => __pbn__Cdkstr != null;
        public void ResetCdkstr() => __pbn__Cdkstr = null;
        private string __pbn__Cdkstr;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CurtUIEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCUIEvent)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCUIEvent;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"eventlist")]
        public global::System.Collections.Generic.List<UIEvent> Eventlists { get; } = new global::System.Collections.Generic.List<UIEvent>();

        [global::ProtoBuf.ProtoContract()]
        public partial class UIEvent : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(2, Name = @"uiidx")]
            public uint Uiidx
            {
                get => __pbn__Uiidx.GetValueOrDefault();
                set => __pbn__Uiidx = value;
            }
            public bool ShouldSerializeUiidx() => __pbn__Uiidx != null;
            public void ResetUiidx() => __pbn__Uiidx = null;
            private uint? __pbn__Uiidx;

            [global::ProtoBuf.ProtoMember(3)]
            public uint eventNum
            {
                get => __pbn__eventNum.GetValueOrDefault();
                set => __pbn__eventNum = value;
            }
            public bool ShouldSerializeeventNum() => __pbn__eventNum != null;
            public void ReseteventNum() => __pbn__eventNum = null;
            private uint? __pbn__eventNum;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskRecoinRune : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskRecoinRune)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskRecoinRune;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"rune_id")]
        public uint RuneId
        {
            get => __pbn__RuneId.GetValueOrDefault();
            set => __pbn__RuneId = value;
        }
        public bool ShouldSerializeRuneId() => __pbn__RuneId != null;
        public void ResetRuneId() => __pbn__RuneId = null;
        private uint? __pbn__RuneId;

        [global::ProtoBuf.ProtoMember(3, Name = @"pay_type")]
        public uint PayType
        {
            get => __pbn__PayType.GetValueOrDefault();
            set => __pbn__PayType = value;
        }
        public bool ShouldSerializePayType() => __pbn__PayType != null;
        public void ResetPayType() => __pbn__PayType = null;
        private uint? __pbn__PayType;

        [global::ProtoBuf.ProtoMember(4, Name = @"cost")]
        public uint Cost
        {
            get => __pbn__Cost.GetValueOrDefault();
            set => __pbn__Cost = value;
        }
        public bool ShouldSerializeCost() => __pbn__Cost != null;
        public void ResetCost() => __pbn__Cost = null;
        private uint? __pbn__Cost;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlackListOnlineInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskBlackListOnlineInfo)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskBlackListOnlineInfo;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddCSGMCmd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCGmCmd)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCGmCmd;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"gmcmd")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Gmcmd
        {
            get => __pbn__Gmcmd ?? "";
            set => __pbn__Gmcmd = value;
        }
        public bool ShouldSerializeGmcmd() => __pbn__Gmcmd != null;
        public void ResetGmcmd() => __pbn__Gmcmd = null;
        private string __pbn__Gmcmd;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NotifyOneMatchNeedOneRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCNotifyOneMatchNeedOneRet)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCNotifyOneMatchNeedOneRet;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"mapid")]
        public uint Mapid
        {
            get => __pbn__Mapid.GetValueOrDefault();
            set => __pbn__Mapid = value;
        }
        public bool ShouldSerializeMapid() => __pbn__Mapid != null;
        public void ResetMapid() => __pbn__Mapid = null;
        private uint? __pbn__Mapid;

        [global::ProtoBuf.ProtoMember(3, Name = @"fightid")]
        public uint Fightid
        {
            get => __pbn__Fightid.GetValueOrDefault();
            set => __pbn__Fightid = value;
        }
        public bool ShouldSerializeFightid() => __pbn__Fightid != null;
        public void ResetFightid() => __pbn__Fightid = null;
        private uint? __pbn__Fightid;

        [global::ProtoBuf.ProtoMember(4)]
        public bool isAccept
        {
            get => __pbn__isAccept.GetValueOrDefault();
            set => __pbn__isAccept = value;
        }
        public bool ShouldSerializeisAccept() => __pbn__isAccept != null;
        public void ResetisAccept() => __pbn__isAccept = null;
        private bool? __pbn__isAccept;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskChangeheaderId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskChangeheaderId)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskChangeheaderId;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"newheaderid")]
        public uint Newheaderid
        {
            get => __pbn__Newheaderid.GetValueOrDefault();
            set => __pbn__Newheaderid = value;
        }
        public bool ShouldSerializeNewheaderid() => __pbn__Newheaderid != null;
        public void ResetNewheaderid() => __pbn__Newheaderid = null;
        private uint? __pbn__Newheaderid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeNickName : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskChangeNickName)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskChangeNickName;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"newnickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Newnickname
        {
            get => __pbn__Newnickname ?? "";
            set => __pbn__Newnickname = value;
        }
        public bool ShouldSerializeNewnickname() => __pbn__Newnickname != null;
        public void ResetNewnickname() => __pbn__Newnickname = null;
        private string __pbn__Newnickname;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskCreateMatchTeam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskCreateMatchTeam)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskCreateMatchTeam;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"matchtype")]
        public uint Matchtype
        {
            get => __pbn__Matchtype.GetValueOrDefault();
            set => __pbn__Matchtype = value;
        }
        public bool ShouldSerializeMatchtype() => __pbn__Matchtype != null;
        public void ResetMatchtype() => __pbn__Matchtype = null;
        private uint? __pbn__Matchtype;

        [global::ProtoBuf.ProtoMember(3, Name = @"mapid")]
        public uint Mapid
        {
            get => __pbn__Mapid.GetValueOrDefault();
            set => __pbn__Mapid = value;
        }
        public bool ShouldSerializeMapid() => __pbn__Mapid != null;
        public void ResetMapid() => __pbn__Mapid = null;
        private uint? __pbn__Mapid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskAddMatchTeam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskAddMatchTeam)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskAddMatchTeam;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string friendsNickName
        {
            get => __pbn__friendsNickName ?? "";
            set => __pbn__friendsNickName = value;
        }
        public bool ShouldSerializefriendsNickName() => __pbn__friendsNickName != null;
        public void ResetfriendsNickName() => __pbn__friendsNickName = null;
        private string __pbn__friendsNickName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskRemoveMatchTeam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskRemoveMatchTeam)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskRemoveMatchTeam;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskInviteJoinMatchTeam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskInviteJoinMatchTeam)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskInviteJoinMatchTeam;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string friendsNickName
        {
            get => __pbn__friendsNickName ?? "";
            set => __pbn__friendsNickName = value;
        }
        public bool ShouldSerializefriendsNickName() => __pbn__friendsNickName != null;
        public void ResetfriendsNickName() => __pbn__friendsNickName = null;
        private string __pbn__friendsNickName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskStartMatch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskStartMatch)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskStartMatch;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskStopMatch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskStopMatch)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskStopMatch;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestMatchTeamList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCRequestMatchTeamList)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCRequestMatchTeamList;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskGoodscfg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskGoodscfg)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskGoodscfg;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskCSCreateGuideBattle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskGuideBattle)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskGuideBattle;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"mapid")]
        public int Mapid
        {
            get => __pbn__Mapid.GetValueOrDefault();
            set => __pbn__Mapid = value;
        }
        public bool ShouldSerializeMapid() => __pbn__Mapid != null;
        public void ResetMapid() => __pbn__Mapid = null;
        private int? __pbn__Mapid;

        [global::ProtoBuf.ProtoMember(3, Name = @"ntype")]
        [global::System.ComponentModel.DefaultValue(Guidetype.First)]
        public Guidetype Ntype
        {
            get => __pbn__Ntype ?? Guidetype.First;
            set => __pbn__Ntype = value;
        }
        public bool ShouldSerializeNtype() => __pbn__Ntype != null;
        public void ResetNtype() => __pbn__Ntype = null;
        private Guidetype? __pbn__Ntype;

        [global::ProtoBuf.ProtoContract(Name = @"guidetype")]
        public enum Guidetype
        {
            [global::ProtoBuf.ProtoEnum(Name = @"first")]
            First = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"second")]
            Second = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"other")]
            Other = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskQuickBattle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskQuickBattle)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskQuickBattle;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"mapid")]
        public int Mapid
        {
            get => __pbn__Mapid.GetValueOrDefault();
            set => __pbn__Mapid = value;
        }
        public bool ShouldSerializeMapid() => __pbn__Mapid != null;
        public void ResetMapid() => __pbn__Mapid = null;
        private int? __pbn__Mapid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskStopQuickBattle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskStopQuickBattle)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskStopQuickBattle;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskCreateRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskCreateRoom)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskCreateRoom;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"mapid")]
        public int Mapid
        {
            get => __pbn__Mapid.GetValueOrDefault();
            set => __pbn__Mapid = value;
        }
        public bool ShouldSerializeMapid() => __pbn__Mapid != null;
        public void ResetMapid() => __pbn__Mapid = null;
        private int? __pbn__Mapid;

        [global::ProtoBuf.ProtoMember(3, Name = @"passwd")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passwd
        {
            get => __pbn__Passwd ?? "";
            set => __pbn__Passwd = value;
        }
        public bool ShouldSerializePasswd() => __pbn__Passwd != null;
        public void ResetPasswd() => __pbn__Passwd = null;
        private string __pbn__Passwd;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskAddRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskAddRoom)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskAddRoom;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"battleid")]
        public ulong Battleid
        {
            get => __pbn__Battleid.GetValueOrDefault();
            set => __pbn__Battleid = value;
        }
        public bool ShouldSerializeBattleid() => __pbn__Battleid != null;
        public void ResetBattleid() => __pbn__Battleid = null;
        private ulong? __pbn__Battleid;

        [global::ProtoBuf.ProtoMember(3, Name = @"passwd")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passwd
        {
            get => __pbn__Passwd ?? "";
            set => __pbn__Passwd = value;
        }
        public bool ShouldSerializePasswd() => __pbn__Passwd != null;
        public void ResetPasswd() => __pbn__Passwd = null;
        private string __pbn__Passwd;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskLeaveRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskLeaveRoom)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskLeaveRoom;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskChangeRoomSeat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskChangeRoomSeat)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskChangeRoomSeat;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"newpos")]
        public int Newpos
        {
            get => __pbn__Newpos.GetValueOrDefault();
            set => __pbn__Newpos = value;
        }
        public bool ShouldSerializeNewpos() => __pbn__Newpos != null;
        public void ResetNewpos() => __pbn__Newpos = null;
        private int? __pbn__Newpos;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskReadyRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskReadyRoom)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskReadyRoom;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskCancelRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskCancelRoom)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskCancelRoom;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskStartRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskStartRoom)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskStartRoom;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskReEnterRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskReEnterRoom)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskReEnterRoom;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskChatInRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskChatInRoom)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskChatInRoom;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"chat")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Chat
        {
            get => __pbn__Chat ?? "";
            set => __pbn__Chat = value;
        }
        public bool ShouldSerializeChat() => __pbn__Chat != null;
        public void ResetChat() => __pbn__Chat = null;
        private string __pbn__Chat;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskGetMailGift : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskGetMailGift)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskGetMailGift;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2)]
        public int mailId
        {
            get => __pbn__mailId.GetValueOrDefault();
            set => __pbn__mailId = value;
        }
        public bool ShouldSerializemailId() => __pbn__mailId != null;
        public void ResetmailId() => __pbn__mailId = null;
        private int? __pbn__mailId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskMailInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskMailInfo)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskMailInfo;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2)]
        public int mailId
        {
            get => __pbn__mailId.GetValueOrDefault();
            set => __pbn__mailId = value;
        }
        public bool ShouldSerializemailId() => __pbn__mailId != null;
        public void ResetmailId() => __pbn__mailId = null;
        private int? __pbn__mailId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskBuyGoods : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskBuyGoods)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskBuyGoods;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"commondityid")]
        public int Commondityid
        {
            get => __pbn__Commondityid.GetValueOrDefault();
            set => __pbn__Commondityid = value;
        }
        public bool ShouldSerializeCommondityid() => __pbn__Commondityid != null;
        public void ResetCommondityid() => __pbn__Commondityid = null;
        private int? __pbn__Commondityid;

        [global::ProtoBuf.ProtoMember(3, Name = @"consumetype")]
        public int Consumetype
        {
            get => __pbn__Consumetype.GetValueOrDefault();
            set => __pbn__Consumetype = value;
        }
        public bool ShouldSerializeConsumetype() => __pbn__Consumetype != null;
        public void ResetConsumetype() => __pbn__Consumetype = null;
        private int? __pbn__Consumetype;

        [global::ProtoBuf.ProtoMember(4, Name = @"num")]
        public uint Num
        {
            get => __pbn__Num.GetValueOrDefault();
            set => __pbn__Num = value;
        }
        public bool ShouldSerializeNum() => __pbn__Num != null;
        public void ResetNum() => __pbn__Num = null;
        private uint? __pbn__Num;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserAskGetCLReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCUserAskGetCLReward)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCUserAskGetCLReward;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Notice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCNotice)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCNotice;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(NoticeType.TypeNone)]
        public NoticeType Type
        {
            get => __pbn__Type ?? NoticeType.TypeNone;
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private NoticeType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string notice
        {
            get => __pbn__notice ?? "";
            set => __pbn__notice = value;
        }
        public bool ShouldSerializenotice() => __pbn__notice != null;
        public void Resetnotice() => __pbn__notice = null;
        private string __pbn__notice;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskCurtNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskCurtNotice)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskCurtNotice;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(NoticeType.TypeNone)]
        public NoticeType Type
        {
            get => __pbn__Type ?? NoticeType.TypeNone;
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private NoticeType? __pbn__Type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CompleteInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskComleteUserInfo)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskComleteUserInfo;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname
        {
            get => __pbn__Nickname ?? "";
            set => __pbn__Nickname = value;
        }
        public bool ShouldSerializeNickname() => __pbn__Nickname != null;
        public void ResetNickname() => __pbn__Nickname = null;
        private string __pbn__Nickname;

        [global::ProtoBuf.ProtoMember(3, Name = @"headid")]
        public int Headid
        {
            get => __pbn__Headid.GetValueOrDefault();
            set => __pbn__Headid = value;
        }
        public bool ShouldSerializeHeadid() => __pbn__Headid != null;
        public void ResetHeadid() => __pbn__Headid = null;
        private int? __pbn__Headid;

        [global::ProtoBuf.ProtoMember(4, Name = @"sex")]
        public int Sex
        {
            get => __pbn__Sex.GetValueOrDefault();
            set => __pbn__Sex = value;
        }
        public bool ShouldSerializeSex() => __pbn__Sex != null;
        public void ResetSex() => __pbn__Sex = null;
        private int? __pbn__Sex;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskAddToSNSList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskAddToSNSList)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskAddToSNSList;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname
        {
            get => __pbn__Nickname ?? "";
            set => __pbn__Nickname = value;
        }
        public bool ShouldSerializeNickname() => __pbn__Nickname != null;
        public void ResetNickname() => __pbn__Nickname = null;
        private string __pbn__Nickname;

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        public int Type
        {
            get => __pbn__Type.GetValueOrDefault();
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskCanInviteFriends : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskCanInviteFriends)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskCanInviteFriends;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskAddToSNSListByID : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskAddToSNSListByID)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskAddToSNSListByID;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"userid")]
        public ulong Userid
        {
            get => __pbn__Userid.GetValueOrDefault();
            set => __pbn__Userid = value;
        }
        public bool ShouldSerializeUserid() => __pbn__Userid != null;
        public void ResetUserid() => __pbn__Userid = null;
        private ulong? __pbn__Userid;

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        public int Type
        {
            get => __pbn__Type.GetValueOrDefault();
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskRemoveFromSNSList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskRemoveFromSNSList)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskRemoveFromSNSList;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"guididx")]
        public ulong Guididx
        {
            get => __pbn__Guididx.GetValueOrDefault();
            set => __pbn__Guididx = value;
        }
        public bool ShouldSerializeGuididx() => __pbn__Guididx != null;
        public void ResetGuididx() => __pbn__Guididx = null;
        private ulong? __pbn__Guididx;

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        public int Type
        {
            get => __pbn__Type.GetValueOrDefault();
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskSendMsgToUser : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskSendMsgToUser)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskSendMsgToUser;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"guididx")]
        public ulong Guididx
        {
            get => __pbn__Guididx.GetValueOrDefault();
            set => __pbn__Guididx = value;
        }
        public bool ShouldSerializeGuididx() => __pbn__Guididx != null;
        public void ResetGuididx() => __pbn__Guididx = null;
        private ulong? __pbn__Guididx;

        [global::ProtoBuf.ProtoMember(3, Name = @"contents")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Contents
        {
            get => __pbn__Contents ?? "";
            set => __pbn__Contents = value;
        }
        public bool ShouldSerializeContents() => __pbn__Contents != null;
        public void ResetContents() => __pbn__Contents = null;
        private string __pbn__Contents;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskInviteFriendsToBattle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskInviteFriendsToBattle)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskInviteFriendsToBattle;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"battleid")]
        public int Battleid
        {
            get => __pbn__Battleid.GetValueOrDefault();
            set => __pbn__Battleid = value;
        }
        public bool ShouldSerializeBattleid() => __pbn__Battleid != null;
        public void ResetBattleid() => __pbn__Battleid = null;
        private int? __pbn__Battleid;

        [global::ProtoBuf.ProtoMember(3, Name = @"guididx")]
        public ulong Guididx
        {
            get => __pbn__Guididx.GetValueOrDefault();
            set => __pbn__Guididx = value;
        }
        public bool ShouldSerializeGuididx() => __pbn__Guididx != null;
        public void ResetGuididx() => __pbn__Guididx = null;
        private ulong? __pbn__Guididx;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskQueryUserByNickName : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskQueryUserByNickName)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskQueryUserByNickName;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname
        {
            get => __pbn__Nickname ?? "";
            set => __pbn__Nickname = value;
        }
        public bool ShouldSerializeNickname() => __pbn__Nickname != null;
        public void ResetNickname() => __pbn__Nickname = null;
        private string __pbn__Nickname;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GCReplyAddFriendRequst : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCGCReplyAddFriendRequst)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCGCReplyAddFriendRequst;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"guididx")]
        public ulong Guididx
        {
            get => __pbn__Guididx.GetValueOrDefault();
            set => __pbn__Guididx = value;
        }
        public bool ShouldSerializeGuididx() => __pbn__Guididx != null;
        public void ResetGuididx() => __pbn__Guididx = null;
        private ulong? __pbn__Guididx;

        [global::ProtoBuf.ProtoMember(3, Name = @"reply")]
        public int Reply
        {
            get => __pbn__Reply.GetValueOrDefault();
            set => __pbn__Reply = value;
        }
        public bool ShouldSerializeReply() => __pbn__Reply != null;
        public void ResetReply() => __pbn__Reply = null;
        private int? __pbn__Reply;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuideCSStepComp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCCompCSGuideStepId)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCCompCSGuideStepId;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"guidepart")]
        public int Guidepart
        {
            get => __pbn__Guidepart.GetValueOrDefault();
            set => __pbn__Guidepart = value;
        }
        public bool ShouldSerializeGuidepart() => __pbn__Guidepart != null;
        public void ResetGuidepart() => __pbn__Guidepart = null;
        private int? __pbn__Guidepart;

        [global::ProtoBuf.ProtoMember(3, Name = @"bcomp")]
        public bool Bcomp
        {
            get => __pbn__Bcomp.GetValueOrDefault();
            set => __pbn__Bcomp = value;
        }
        public bool ShouldSerializeBcomp() => __pbn__Bcomp != null;
        public void ResetBcomp() => __pbn__Bcomp = null;
        private bool? __pbn__Bcomp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GCReplyInviteToBattle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCGCReplyInviteToBattle)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCGCReplyInviteToBattle;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname
        {
            get => __pbn__Nickname ?? "";
            set => __pbn__Nickname = value;
        }
        public bool ShouldSerializeNickname() => __pbn__Nickname != null;
        public void ResetNickname() => __pbn__Nickname = null;
        private string __pbn__Nickname;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Login : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskLogin)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskLogin;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"sdk")]
        public int Sdk
        {
            get => __pbn__Sdk.GetValueOrDefault();
            set => __pbn__Sdk = value;
        }
        public bool ShouldSerializeSdk() => __pbn__Sdk != null;
        public void ResetSdk() => __pbn__Sdk = null;
        private int? __pbn__Sdk;

        [global::ProtoBuf.ProtoMember(3, Name = @"platform")]
        public int Platform
        {
            get => __pbn__Platform.GetValueOrDefault();
            set => __pbn__Platform = value;
        }
        public bool ShouldSerializePlatform() => __pbn__Platform != null;
        public void ResetPlatform() => __pbn__Platform = null;
        private int? __pbn__Platform;

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(5, Name = @"passwd")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passwd
        {
            get => __pbn__Passwd ?? "";
            set => __pbn__Passwd = value;
        }
        public bool ShouldSerializePasswd() => __pbn__Passwd != null;
        public void ResetPasswd() => __pbn__Passwd = null;
        private string __pbn__Passwd;

        [global::ProtoBuf.ProtoMember(6, Name = @"ipaddress")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ipaddress
        {
            get => __pbn__Ipaddress ?? "";
            set => __pbn__Ipaddress = value;
        }
        public bool ShouldSerializeIpaddress() => __pbn__Ipaddress != null;
        public void ResetIpaddress() => __pbn__Ipaddress = null;
        private string __pbn__Ipaddress;

        [global::ProtoBuf.ProtoMember(7, Name = @"equimentid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Equimentid
        {
            get => __pbn__Equimentid ?? "";
            set => __pbn__Equimentid = value;
        }
        public bool ShouldSerializeEquimentid() => __pbn__Equimentid != null;
        public void ResetEquimentid() => __pbn__Equimentid = null;
        private string __pbn__Equimentid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserGameInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskUserGameInfo)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskUserGameInfo;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuyRunes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCBUYRunes)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCBUYRunes;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"typeid")]
        public int Typeid
        {
            get => __pbn__Typeid.GetValueOrDefault();
            set => __pbn__Typeid = value;
        }
        public bool ShouldSerializeTypeid() => __pbn__Typeid != null;
        public void ResetTypeid() => __pbn__Typeid = null;
        private int? __pbn__Typeid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EuipRunes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCEuipRunes)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCEuipRunes;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"runeid")]
        public uint Runeid
        {
            get => __pbn__Runeid.GetValueOrDefault();
            set => __pbn__Runeid = value;
        }
        public bool ShouldSerializeRuneid() => __pbn__Runeid != null;
        public void ResetRuneid() => __pbn__Runeid = null;
        private uint? __pbn__Runeid;

        [global::ProtoBuf.ProtoMember(3, Name = @"topos")]
        public int Topos
        {
            get => __pbn__Topos.GetValueOrDefault();
            set => __pbn__Topos = value;
        }
        public bool ShouldSerializeTopos() => __pbn__Topos != null;
        public void ResetTopos() => __pbn__Topos = null;
        private int? __pbn__Topos;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnEuipRunes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCUnloadRunes)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCUnloadRunes;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"page")]
        public int Page
        {
            get => __pbn__Page.GetValueOrDefault();
            set => __pbn__Page = value;
        }
        public bool ShouldSerializePage() => __pbn__Page != null;
        public void ResetPage() => __pbn__Page = null;
        private int? __pbn__Page;

        [global::ProtoBuf.ProtoMember(3, Name = @"pos")]
        public int Pos
        {
            get => __pbn__Pos.GetValueOrDefault();
            set => __pbn__Pos = value;
        }
        public bool ShouldSerializePos() => __pbn__Pos != null;
        public void ResetPos() => __pbn__Pos = null;
        private int? __pbn__Pos;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ComposeRunes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCComposeRunes)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCComposeRunes;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"runesid")]
        public uint[] Runesids { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReconnectToGame : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskReconnectGame)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskReconnectGame;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"passwd")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passwd
        {
            get => __pbn__Passwd ?? "";
            set => __pbn__Passwd = value;
        }
        public bool ShouldSerializePasswd() => __pbn__Passwd != null;
        public void ResetPasswd() => __pbn__Passwd = null;
        private string __pbn__Passwd;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ComGuideStepID : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskGuideStepId)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskGuideStepId;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public int Type
        {
            get => __pbn__Type.GetValueOrDefault();
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

        [global::ProtoBuf.ProtoMember(3, Name = @"step")]
        public int Step
        {
            get => __pbn__Step.GetValueOrDefault();
            set => __pbn__Step = value;
        }
        public bool ShouldSerializeStep() => __pbn__Step != null;
        public void ResetStep() => __pbn__Step = null;
        private int? __pbn__Step;

        [global::ProtoBuf.ProtoMember(4, Name = @"state")]
        public int State
        {
            get => __pbn__State.GetValueOrDefault();
            set => __pbn__State = value;
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private int? __pbn__State;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AskRoomList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgnum")]
        [global::System.ComponentModel.DefaultValue(MsgNum.eMsgToGSToCSFromGCAskRoomList)]
        public MsgNum Msgnum
        {
            get => __pbn__Msgnum ?? MsgNum.eMsgToGSToCSFromGCAskRoomList;
            set => __pbn__Msgnum = value;
        }
        public bool ShouldSerializeMsgnum() => __pbn__Msgnum != null;
        public void ResetMsgnum() => __pbn__Msgnum = null;
        private MsgNum? __pbn__Msgnum;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum MsgNum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_Begin")]
        eMsgToGSToCSFromGCBegin = 8191,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskLogin")]
        eMsgToGSToCSFromGCAskLogin = 8193,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskReconnectGame")]
        eMsgToGSToCSFromGCAskReconnectGame = 8194,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskComleteUserInfo")]
        eMsgToGSToCSFromGCAskComleteUserInfo = 8195,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskUserGameInfo")]
        eMsgToGSToCSFromGCAskUserGameInfo = 8196,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_UserAskGetCLReward")]
        eMsgToGSToCSFromGCUserAskGetCLReward = 8197,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_Notice")]
        eMsgToGSToCSFromGCNotice = 8200,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskCurtNotice")]
        eMsgToGSToCSFromGCAskCurtNotice = 8201,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskAddToSNSList")]
        eMsgToGSToCSFromGCAskAddToSNSList = 8210,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskRemoveFromSNSList")]
        eMsgToGSToCSFromGCAskRemoveFromSNSList = 8211,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskSendMsgToUser")]
        eMsgToGSToCSFromGCAskSendMsgToUser = 8212,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskInviteFriendsToBattle")]
        eMsgToGSToCSFromGCAskInviteFriendsToBattle = 8213,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskQueryUserByNickName")]
        eMsgToGSToCSFromGCAskQueryUserByNickName = 8214,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_GCReplyAddFriendRequst")]
        eMsgToGSToCSFromGCGCReplyAddFriendRequst = 8215,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_GCReplyInviteToBattle")]
        eMsgToGSToCSFromGCGCReplyInviteToBattle = 8216,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskAddToSNSListByID")]
        eMsgToGSToCSFromGCAskAddToSNSListByID = 8217,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskCanInviteFriends")]
        eMsgToGSToCSFromGCAskCanInviteFriends = 8218,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskBlackListOnlineInfo")]
        eMsgToGSToCSFromGCAskBlackListOnlineInfo = 8502,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_BUYRunes")]
        eMsgToGSToCSFromGCBUYRunes = 8220,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_EuipRunes")]
        eMsgToGSToCSFromGCEuipRunes = 8221,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_UnloadRunes")]
        eMsgToGSToCSFromGCUnloadRunes = 8222,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_ComposeRunes")]
        eMsgToGSToCSFromGCComposeRunes = 8223,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskBuyGoods")]
        eMsgToGSToCSFromGCAskBuyGoods = 8224,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskRecoinRune")]
        eMsgToGSToCSFromGCAskRecoinRune = 8503,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskMailInfo")]
        eMsgToGSToCSFromGCAskMailInfo = 8230,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskGetMailGift")]
        eMsgToGSToCSFromGCAskGetMailGift = 8231,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskGuideBattle")]
        eMsgToGSToCSFromGCAskGuideBattle = 8240,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskGuideStepId")]
        eMsgToGSToCSFromGCAskGuideStepId = 8241,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_CompCSGuideStepId")]
        eMsgToGSToCSFromGCCompCSGuideStepId = 8242,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskQuickBattle")]
        eMsgToGSToCSFromGCAskQuickBattle = 8250,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskStopQuickBattle")]
        eMsgToGSToCSFromGCAskStopQuickBattle = 8251,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskCreateRoom")]
        eMsgToGSToCSFromGCAskCreateRoom = 8260,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskAddRoom")]
        eMsgToGSToCSFromGCAskAddRoom = 8261,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskLeaveRoom")]
        eMsgToGSToCSFromGCAskLeaveRoom = 8262,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskChangeRoomSeat")]
        eMsgToGSToCSFromGCAskChangeRoomSeat = 8263,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskReadyRoom")]
        eMsgToGSToCSFromGCAskReadyRoom = 8264,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskCancelRoom")]
        eMsgToGSToCSFromGCAskCancelRoom = 8265,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskStartRoom")]
        eMsgToGSToCSFromGCAskStartRoom = 8266,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskChatInRoom")]
        eMsgToGSToCSFromGCAskChatInRoom = 8267,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskReEnterRoom")]
        eMsgToGSToCSFromGCAskReEnterRoom = 8268,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskRoomList")]
        eMsgToGSToCSFromGCAskRoomList = 8269,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskGoodscfg")]
        eMsgToGSToCSFromGCAskGoodscfg = 8270,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskCreateMatchTeam")]
        eMsgToGSToCSFromGCAskCreateMatchTeam = 8280,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskAddMatchTeam")]
        eMsgToGSToCSFromGCAskAddMatchTeam = 8281,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskRemoveMatchTeam")]
        eMsgToGSToCSFromGCAskRemoveMatchTeam = 8282,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskInviteJoinMatchTeam")]
        eMsgToGSToCSFromGCAskInviteJoinMatchTeam = 8283,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskStartMatch")]
        eMsgToGSToCSFromGCAskStartMatch = 8284,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskStopMatch")]
        eMsgToGSToCSFromGCAskStopMatch = 8285,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskChangeNickName")]
        eMsgToGSToCSFromGCAskChangeNickName = 8286,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_RequestMatchTeamList")]
        eMsgToGSToCSFromGCRequestMatchTeamList = 8287,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_NotifyOneMatchNeedOneRet")]
        eMsgToGSToCSFromGCNotifyOneMatchNeedOneRet = 8288,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskOneTaskRewards")]
        eMsgToGSToCSFromGCAskOneTaskRewards = 8290,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_AskChangeheaderId")]
        eMsgToGSToCSFromGCAskChangeheaderId = 8500,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_CDKReq")]
        eMsgToGSToCSFromGCCDKReq = 8505,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_GmCmd")]
        eMsgToGSToCSFromGCGmCmd = 8501,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_UIEvent")]
        eMsgToGSToCSFromGCUIEvent = 8550,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGSToCSFromGC_End")]
        eMsgToGSToCSFromGCEnd = 9000,
    }

    [global::ProtoBuf.ProtoContract(Name = @"notice_type")]
    public enum NoticeType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"type_none")]
        TypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"type_1")]
        Type1 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"type_2")]
        Type2 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"type_3")]
        Type3 = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
