// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: LSToGC.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace LSToGC
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgid")]
        [global::System.ComponentModel.DefaultValue(MsgID.eMsgToGCFromLSNotifyLoginResult)]
        public MsgID Msgid
        {
            get => __pbn__Msgid ?? MsgID.eMsgToGCFromLSNotifyLoginResult;
            set => __pbn__Msgid = value;
        }
        public bool ShouldSerializeMsgid() => __pbn__Msgid != null;
        public void ResetMsgid() => __pbn__Msgid = null;
        private MsgID? __pbn__Msgid;

        [global::ProtoBuf.ProtoMember(2, Name = @"result")]
        public int Result
        {
            get => __pbn__Result.GetValueOrDefault();
            set => __pbn__Result = value;
        }
        public bool ShouldSerializeResult() => __pbn__Result != null;
        public void ResetResult() => __pbn__Result = null;
        private int? __pbn__Result;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ServerName
        {
            get => __pbn__ServerName ?? "";
            set => __pbn__ServerName = value;
        }
        public bool ShouldSerializeServerName() => __pbn__ServerName != null;
        public void ResetServerName() => __pbn__ServerName = null;
        private string __pbn__ServerName;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ServerAddr
        {
            get => __pbn__ServerAddr ?? "";
            set => __pbn__ServerAddr = value;
        }
        public bool ShouldSerializeServerAddr() => __pbn__ServerAddr != null;
        public void ResetServerAddr() => __pbn__ServerAddr = null;
        private string __pbn__ServerAddr;

        [global::ProtoBuf.ProtoMember(3)]
        public int ServerPort
        {
            get => __pbn__ServerPort.GetValueOrDefault();
            set => __pbn__ServerPort = value;
        }
        public bool ShouldSerializeServerPort() => __pbn__ServerPort != null;
        public void ResetServerPort() => __pbn__ServerPort = null;
        private int? __pbn__ServerPort;

        [global::ProtoBuf.ProtoMember(4)]
        public int ServerState
        {
            get => __pbn__ServerState.GetValueOrDefault();
            set => __pbn__ServerState = value;
        }
        public bool ShouldSerializeServerState() => __pbn__ServerState != null;
        public void ResetServerState() => __pbn__ServerState = null;
        private int? __pbn__ServerState;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerBSAddr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msgid")]
        [global::System.ComponentModel.DefaultValue(MsgID.eMsgToGCFromLSNotifyServerBSAddr)]
        public MsgID Msgid
        {
            get => __pbn__Msgid ?? MsgID.eMsgToGCFromLSNotifyServerBSAddr;
            set => __pbn__Msgid = value;
        }
        public bool ShouldSerializeMsgid() => __pbn__Msgid != null;
        public void ResetMsgid() => __pbn__Msgid = null;
        private MsgID? __pbn__Msgid;

        [global::ProtoBuf.ProtoMember(2, Name = @"serverinfo")]
        public global::System.Collections.Generic.List<ServerInfo> Serverinfoes { get; } = new global::System.Collections.Generic.List<ServerInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum MsgID
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGCFromLS_NotifyLoginResult")]
        eMsgToGCFromLSNotifyLoginResult = 512,
        [global::ProtoBuf.ProtoEnum(Name = @"eMsgToGCFromLS_NotifyServerBSAddr")]
        eMsgToGCFromLSNotifyServerBSAddr = 513,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
